name: Republish

on:
  schedule:
    - cron: "0 0 * * *" # Run at 00:00 every day
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub pages rebuild
        run: |
          curl --fail --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
            --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
